export const OUTREACH_PATH = '/outreach'
export const OUTREACH_LOGIN_PATH = '/outreach/login'
export const OUTREACH_SIGNUP_PATH = '/outreach/signup'
export const OUTREACH_JOIN_PATH = '/outreach/join'
export const OUTREACH_VERIFY_PATH = '/outreach/verify'
